repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_jsr305: com.google.code.findbugs:jsr305:jar:2.0.1
  getopt4j: org.realityforge.getopt4j:getopt4j:jar:1.1
  javax_json: org.glassfish:javax.json:jar:1.0.3

  #
  # Mocking library
  mockito: org.mockito:mockito-all:jar:1.9.5
