gems:
  - buildr = 1.4.6

repositories:
  remote:
   - http://repo1.maven.org/maven2
  release_to:
    url: http://repo.fire.dse.vic.gov.au/content/repositories/releases/
    username: upload

artifacts:
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  getopt4j: org.realityforge:getopt4j:jar:1.0
  json_simple: com.googlecode.json-simple:json-simple:jar:1.1

  #
  # Mocking library
  mockito: org.mockito:mockito-all:jar:1.8.5
